language: go
sudo: false
go:
    - 1.4
env:
    - GOMAXPROCS=1
before_install: ./scripts/hack/symlink-gopath-travisci
install: make get-deps
script:
    # Full tests require building/running docker containers; short only for now
    - make short-test
